package ru.bartwell.kick.module.firebase.cloudmessaging.core.persist

import ru.bartwell.kick.module.firebase.cloudmessaging.core.data.FirebaseMessage

internal data class FirebaseMessageEntity(
    val id: Long = 0,
    val title: String? = null,
    val body: String? = null,
    val data: Map<String, String> = emptyMap(),
    val from: String? = null,
    val to: String? = null,
    val messageId: String? = null,
    val sentTimeMillis: Long? = null,
    val collapseKey: String? = null,
    val channelId: String? = null,
    val category: String? = null,
    val threadId: String? = null,
    val badge: String? = null,
    val sound: String? = null,
    val tag: String? = null,
    val imageUrl: String? = null,
    val priority: String? = null,
    val ttlSeconds: Long? = null,
    val raw: Map<String, String> = emptyMap(),
    val receivedAtMillis: Long,
)

internal fun FirebaseMessage.toEntity(): FirebaseMessageEntity = FirebaseMessageEntity(
    title = title,
    body = body,
    data = data,
    from = from,
    to = to,
    messageId = messageId,
    sentTimeMillis = sentTimeMillis,
    collapseKey = collapseKey,
    channelId = channelId,
    category = category,
    threadId = threadId,
    badge = badge,
    sound = sound,
    tag = tag,
    imageUrl = imageUrl,
    priority = priority,
    ttlSeconds = ttlSeconds,
    raw = raw,
    receivedAtMillis = receivedAtMillis,
)

internal fun FirebaseMessageEntity.toDomain(): FirebaseMessage = FirebaseMessage(
    title = title,
    body = body,
    data = data,
    from = from,
    to = to,
    messageId = messageId,
    sentTimeMillis = sentTimeMillis,
    collapseKey = collapseKey,
    channelId = channelId,
    category = category,
    threadId = threadId,
    badge = badge,
    sound = sound,
    tag = tag,
    imageUrl = imageUrl,
    priority = priority,
    ttlSeconds = ttlSeconds,
    raw = raw,
    receivedAtMillis = receivedAtMillis,
)
